uses GraphABC;
var marks: array [1..49] of string = ('Acura'
,'Alfa Romeo'
,'Audi'
,'Bentley'
,'Bogdan'
,'Buick'
,'Cadillac'
,'Chery'
,'Chevrolet'
,'Citro¸n'
,'Daewoo'
,'Daihatsu'
,'Dodge'
,'Faw'
,'Ferrari'
,'Gaz'
,'Hafei'
,'Haima'
,'Honda'
,'Hyundai'
,'infiniti'
,'Iran Khodro'
,'Jaguar'
,'Kamaz'
,'Koenigsegg'
,'Lamborghini'
,'Lexus'
,'Lincoln'
,'Maserati'
,'Mazda'
,'Mercedes'
,'Mercury'
,'Mini'
,'Mitsubishi'
,'Moskvich'
,'Opel'
,'Peugeot'
,'Pontiac'
,'Porshe'
,'Renault'
,'SAAB'
,'Saturn'
,'Scoda'
,'Seat'
,'Subaru'
,'Toyota'
,'Volkswagen'
,'F1'
);

var way: array [1..49] of string = ('Acura.jpg'
,'Alfa Romeo.jpg'
,'Audi.jpg'
,'Bentley.jpg'
,'Bogdan.jpg'
,'Buick.jpg'
,'Cadillac.jpg'
,'Chery.jpg'
,'Chevrolet.jpg'
,'Citro¸n.jpg'
,'Daewoo.jpg'
,'Daihatsu.jpg'
,'Dodge.jpg'
,'Faw.jpg'
,'Ferrari.jpg'
,'Gaz.jpg'
,'Hafei.jpg'
,'Haima.jpg'
,'Honda.jpg'
,'Hyundai.jpg'
,'infiniti.jpg'
,'Iran Khodro.jpg'
,'Jaguar.jpg'
,'Kamaz.jpg'
,'Koenigsegg.jpg'
,'Lamborghini.jpg'
,'Lexus.jpg'
,'Lincoln.jpg'
,'Maserati.jpg'
,'Mazda.jpg'
,'Mercedes.jpg'
,'Mercury.jpg'
,'Mini.jpg'
,'Mitsubishi.jpg'
,'Moskvich.jpg'
,'Opel.jpg'
,'Peugeot.jpg'
,'Pontiac.jpg'
,'Porshe.jpg'
,'Renault.jpg'
,'Saab.jpg'
,'Saturn.jpg'
,'Scoda.jpg'
,'Seat.jpg'
,'Subaru.jpg'
,'Toyota.jpg'
,'Volkswagen.jpg'
,'F1.jpg'
);


var way: array [1..49] of string = (

begin
  var Pict: Picture;
  Pict := Picture.Create('New\'+way[49]);
  Pict.Load('New\'+way[49]);
  Pict.Transparent := True;
  Pict.Draw(0, 0)
  //print(way[49]);
end.